import { Achievement } from '../types/achievement'

export const ACHIEVEMENTS: Achievement[] = [
  // ===================== PROGRESSION (8) =====================
  {
    id: 'ach_first_day',
    name: '第一天',
    description: '完成与小浣熊相处的第一天。',
    emoji: '🌱',
    category: 'progression',
    hidden: false,
    conditions: [{ type: 'days_played', dayCount: 1 }],
    rewards: { coins: 50, exp: 30 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_one_week',
    name: '一周老手',
    description: '坚持与小浣熊一起工作满7天。',
    emoji: '📅',
    category: 'progression',
    hidden: false,
    conditions: [{ type: 'days_played', dayCount: 7 }],
    rewards: { coins: 150, exp: 100, rewardTickets: 1 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_one_month',
    name: '老伙伴',
    description: '坚持与小浣熊一起工作满30天。',
    emoji: '🏠',
    category: 'progression',
    hidden: false,
    conditions: [{ type: 'days_played', dayCount: 30 }],
    rewards: { coins: 500, exp: 300, rewardTickets: 3 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_level_5',
    name: '渐入佳境',
    description: '玩家等级达到5级。',
    emoji: '⭐',
    category: 'progression',
    hidden: false,
    conditions: [{ type: 'player_level', level: 5 }],
    rewards: { coins: 200, exp: 100 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_level_10',
    name: '资深训练师',
    description: '玩家等级达到10级。',
    emoji: '🌟',
    category: 'progression',
    hidden: false,
    conditions: [{ type: 'player_level', level: 10 }],
    rewards: { coins: 500, exp: 300, rewardTickets: 2 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_login_streak_7',
    name: '连续打卡达人',
    description: '连续登录7天。',
    emoji: '🔥',
    category: 'progression',
    hidden: false,
    conditions: [{ type: 'login_streak', consecutive: 7 }],
    rewards: { coins: 200, exp: 100, rewardTickets: 1 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_login_streak_30',
    name: '月度签到王',
    description: '连续登录30天。',
    emoji: '📆',
    category: 'progression',
    hidden: false,
    conditions: [{ type: 'login_streak', consecutive: 30 }],
    rewards: { coins: 800, exp: 500, rewardTickets: 5, realRewardEligible: true },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_raccoon_level_5',
    name: '小浣熊成长记',
    description: '帮助小浣熊达到5级。',
    emoji: '🦝',
    category: 'progression',
    hidden: false,
    conditions: [{ type: 'raccoon_level', level: 5 }],
    rewards: { coins: 250, exp: 150, unlockContent: 'trait_genius_unlock' },
    claimed: false,
    progress: 0,
  },

  // ===================== TASK_MASTER (8) =====================
  {
    id: 'ach_first_task',
    name: '破冰之作',
    description: '完成第一个任务。',
    emoji: '🎯',
    category: 'task_master',
    hidden: false,
    conditions: [{ type: 'tasks_completed', count: 1 }],
    rewards: { coins: 30, exp: 20 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_10_tasks',
    name: '任务熟手',
    description: '累计完成10个任务。',
    emoji: '📝',
    category: 'task_master',
    hidden: false,
    conditions: [{ type: 'tasks_completed', count: 10 }],
    rewards: { coins: 100, exp: 60 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_50_tasks',
    name: '任务专家',
    description: '累计完成50个任务。',
    emoji: '🗂️',
    category: 'task_master',
    hidden: false,
    conditions: [{ type: 'tasks_completed', count: 50 }],
    rewards: { coins: 400, exp: 250, rewardTickets: 2 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_first_perfect',
    name: '完美主义初体验',
    description: '首次在任务中获得"完美"评级。',
    emoji: '💯',
    category: 'task_master',
    hidden: false,
    conditions: [{ type: 'task_grade', taskDifficulty: 'any', count: 1 }],
    rewards: { coins: 150, exp: 80, items: ['lucky_charm'] },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_10_perfect',
    name: '精益求精',
    description: '累计获得10次"完美"评级。',
    emoji: '✨',
    category: 'task_master',
    hidden: false,
    conditions: [{ type: 'task_grade_perfect_count', count: 10 }],
    rewards: { coins: 500, exp: 300, rewardTickets: 3 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_all_categories',
    name: '全能选手',
    description: '在所有8个任务类别中各完成至少一个任务。',
    emoji: '🌈',
    category: 'task_master',
    hidden: false,
    conditions: [
      { type: 'task_category', taskCategory: 'writing', count: 1 },
      { type: 'task_category', taskCategory: 'analysis', count: 1 },
      { type: 'task_category', taskCategory: 'creative', count: 1 },
      { type: 'task_category', taskCategory: 'research', count: 1 },
      { type: 'task_category', taskCategory: 'planning', count: 1 },
      { type: 'task_category', taskCategory: 'communication', count: 1 },
      { type: 'task_category', taskCategory: 'data', count: 1 },
      { type: 'task_category', taskCategory: 'social', count: 1 },
    ],
    rewards: { coins: 350, exp: 200, rewardTickets: 2 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_first_commission',
    name: '接单达人',
    description: '完成第一个委托任务。',
    emoji: '📋',
    category: 'task_master',
    hidden: false,
    conditions: [{ type: 'task_type_complete', count: 1 }],
    rewards: { coins: 100, exp: 50 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_b_difficulty',
    name: '迎难而上',
    description: '完成一个B难度任务。',
    emoji: '⚔️',
    category: 'task_master',
    hidden: false,
    conditions: [{ type: 'task_difficulty', taskDifficulty: 'B', count: 1 }],
    rewards: { coins: 200, exp: 120, rewardTickets: 1 },
    claimed: false,
    progress: 0,
  },

  // ===================== RACCOON_BONDS (8) =====================
  {
    id: 'ach_trust_50',
    name: '建立信任',
    description: '小浣熊的信任值达到50。',
    emoji: '🤝',
    category: 'raccoon_bonds',
    hidden: false,
    conditions: [{ type: 'raccoon_status', statusKey: 'trust', statusValue: 50 }],
    rewards: { coins: 100, exp: 60 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_trust_80',
    name: '亲密伙伴',
    description: '小浣熊的信任值达到80。',
    emoji: '💛',
    category: 'raccoon_bonds',
    hidden: false,
    conditions: [{ type: 'raccoon_status', statusKey: 'trust', statusValue: 80 }],
    rewards: { coins: 250, exp: 150, rewardTickets: 1 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_trust_100',
    name: '灵魂伴侣',
    description: '小浣熊的信任值达到满值100。',
    emoji: '❤️',
    category: 'raccoon_bonds',
    hidden: false,
    conditions: [{ type: 'raccoon_status', statusKey: 'trust', statusValue: 100 }],
    rewards: { coins: 600, exp: 400, rewardTickets: 5, realRewardEligible: true },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_mood_90',
    name: '开心果',
    description: '让小浣熊的心情保持在90以上。',
    emoji: '😄',
    category: 'raccoon_bonds',
    hidden: false,
    conditions: [{ type: 'raccoon_status', statusKey: 'mood', statusValue: 90 }],
    rewards: { coins: 150, exp: 80 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_all_status_high',
    name: '状态全满！',
    description: '让小浣熊所有状态值同时超过70。',
    emoji: '🌟',
    category: 'raccoon_bonds',
    hidden: false,
    conditions: [
      { type: 'raccoon_status', statusKey: 'hunger', statusValue: 70 },
      { type: 'raccoon_status', statusKey: 'mood', statusValue: 70 },
      { type: 'raccoon_status', statusKey: 'energy', statusValue: 70 },
      { type: 'raccoon_status', statusKey: 'focus', statusValue: 70 },
      { type: 'raccoon_status', statusKey: 'cleanliness', statusValue: 70 },
    ],
    rewards: { coins: 300, exp: 200, rewardTickets: 2 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_feed_10_types',
    name: '美食鉴赏家',
    description: '给小浣熊喂过10种不同的食物。',
    emoji: '🍽️',
    category: 'raccoon_bonds',
    hidden: false,
    conditions: [{ type: 'foods_fed_variety', count: 10 }],
    rewards: { coins: 200, exp: 120 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_groomed_10',
    name: '爱干净小达人',
    description: '给小浣熊梳洗10次。',
    emoji: '🛁',
    category: 'raccoon_bonds',
    hidden: false,
    conditions: [{ type: 'groomed_count', count: 10 }],
    rewards: { coins: 150, exp: 80 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_played_20',
    name: '玩伴认证',
    description: '与小浣熊玩耍20次。',
    emoji: '🎮',
    category: 'raccoon_bonds',
    hidden: false,
    conditions: [{ type: 'played_count', count: 20 }],
    rewards: { coins: 180, exp: 100, rewardTickets: 1 },
    claimed: false,
    progress: 0,
  },

  // ===================== COLLECTOR (6) =====================
  {
    id: 'ach_collect_5_foods',
    name: '初级美食家',
    description: '收集到5种不同的食物。',
    emoji: '🌮',
    category: 'collector',
    hidden: false,
    conditions: [{ type: 'food_collected', count: 5 }],
    rewards: { coins: 80, exp: 40 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_collect_all_foods',
    name: '食物图鉴完成！',
    description: '收集到游戏中所有12种食物。',
    emoji: '🍱',
    category: 'collector',
    hidden: false,
    conditions: [{ type: 'food_collected', count: 12 }],
    rewards: { coins: 400, exp: 250, rewardTickets: 2 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_collect_5_items',
    name: '道具收藏入门',
    description: '收集到5种不同的道具。',
    emoji: '🎒',
    category: 'collector',
    hidden: false,
    conditions: [{ type: 'item_collected', count: 5 }],
    rewards: { coins: 100, exp: 60 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_collect_rare_item',
    name: '稀有收藏家',
    description: '获得一件稀有（rare）道具。',
    emoji: '💎',
    category: 'collector',
    hidden: false,
    conditions: [{ type: 'item_rarity', itemType: 'rare', count: 1 }],
    rewards: { coins: 200, exp: 100 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_collect_legendary',
    name: '传说收藏家',
    description: '获得一件传说（legendary）道具。',
    emoji: '👑',
    category: 'collector',
    hidden: false,
    conditions: [{ type: 'item_rarity', itemType: 'legendary', count: 1 }],
    rewards: { coins: 500, exp: 300, rewardTickets: 3 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_use_all_item_types',
    name: '道具全能',
    description: '使用过所有6种类型的道具。',
    emoji: '🧰',
    category: 'collector',
    hidden: false,
    conditions: [{ type: 'item_types_used', count: 6 }],
    rewards: { coins: 250, exp: 150 },
    claimed: false,
    progress: 0,
  },

  // ===================== TEMPLATE_EXPERT (6) =====================
  {
    id: 'ach_first_template_use',
    name: '模板新手',
    description: '第一次使用工作模板完成任务。',
    emoji: '📄',
    category: 'template_expert',
    hidden: false,
    conditions: [{ type: 'template_used', count: 1 }],
    rewards: { coins: 50, exp: 30 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_template_proficiency_50',
    name: '模板熟练工',
    description: '任意一个模板的熟练度达到50。',
    emoji: '⚙️',
    category: 'template_expert',
    hidden: false,
    conditions: [{ type: 'template_proficiency', statusValue: 50 }],
    rewards: { coins: 150, exp: 80 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_template_proficiency_100',
    name: '模板大师',
    description: '任意一个模板的熟练度达到100（满级）。',
    emoji: '🏅',
    category: 'template_expert',
    hidden: false,
    conditions: [{ type: 'template_proficiency', statusValue: 100 }],
    rewards: { coins: 400, exp: 250, rewardTickets: 2 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_use_all_starter_templates',
    name: '全部入门模板已解锁',
    description: '使用过全部6个初始工作模板。',
    emoji: '📚',
    category: 'template_expert',
    hidden: false,
    conditions: [{ type: 'starter_templates_used', count: 6 }],
    rewards: { coins: 300, exp: 180 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_template_50_uses',
    name: '老司机',
    description: '单个模板累计使用50次。',
    emoji: '🚗',
    category: 'template_expert',
    hidden: false,
    conditions: [{ type: 'single_template_uses', count: 50 }],
    rewards: { coins: 350, exp: 220, rewardTickets: 2 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_create_custom_template',
    name: '我的模板',
    description: '创建第一个自定义工作模板。',
    emoji: '🛠️',
    category: 'template_expert',
    hidden: false,
    conditions: [{ type: 'user_created_templates', count: 1 }],
    rewards: { coins: 200, exp: 120 },
    claimed: false,
    progress: 0,
  },

  // ===================== HIDDEN (10) =====================
  {
    id: 'ach_hidden_low_energy_urgent',
    name: '背水一战',
    description: '在精力值低于20的情况下，成功完成一个紧急（urgent）任务。',
    emoji: '⚡',
    category: 'hidden',
    hidden: true,
    conditions: [
      { type: 'raccoon_status', statusKey: 'energy', statusValue: 20 },
      { type: 'task_urgency_success', count: 1 },
    ],
    rewards: { coins: 500, exp: 300, rewardTickets: 3 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_hidden_perfect_from_low_mood',
    name: '逆境完美',
    description: '在心情值低于30的情况下，获得任务"完美"评级。',
    emoji: '🌪️',
    category: 'hidden',
    hidden: true,
    conditions: [
      { type: 'raccoon_status', statusKey: 'mood', statusValue: 30 },
      { type: 'task_grade_perfect_in_low_mood', count: 1 },
    ],
    rewards: { coins: 400, exp: 250, rewardTickets: 2 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_hidden_all_traits',
    name: '性格百科',
    description: '解锁游戏中所有10种小浣熊性格特质。',
    emoji: '🔮',
    category: 'hidden',
    hidden: true,
    conditions: [{ type: 'traits_unlocked', count: 10 }],
    rewards: { coins: 800, exp: 500, rewardTickets: 5, unlockContent: 'legendary_trait' },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_hidden_trash_rummage_3',
    name: '垃圾桶探险家',
    description: '让小浣熊触发"翻垃圾桶"事件3次（连续不管饱）。',
    emoji: '🗑️',
    category: 'hidden',
    hidden: true,
    conditions: [{ type: 'event_triggered', count: 3 }],
    rewards: { coins: 100, exp: 50, items: ['squirrel_biscuit'] },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_hidden_night_owl',
    name: '夜猫子',
    description: '在一天内让小浣熊完成4个任务（精力全部消耗）。',
    emoji: '🦉',
    category: 'hidden',
    hidden: true,
    conditions: [{ type: 'tasks_in_one_day', count: 4 }],
    rewards: { coins: 200, exp: 100 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_hidden_streak_5_perfect',
    name: '完美连击',
    description: '连续5次任务均获得"完美"评级。',
    emoji: '🌠',
    category: 'hidden',
    hidden: true,
    conditions: [{ type: 'task_grade_perfect_streak', consecutive: 5 }],
    rewards: { coins: 600, exp: 400, rewardTickets: 4 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_hidden_feed_rainbow_candy_5',
    name: '彩虹控',
    description: '给小浣熊喂彩虹糖5次。',
    emoji: '🌈',
    category: 'hidden',
    hidden: true,
    conditions: [{ type: 'food_fed_specific', count: 5 }],
    rewards: { coins: 150, exp: 80 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_hidden_commission_streak',
    name: '委托猎人',
    description: '连续3天都完成委托任务。',
    emoji: '🏹',
    category: 'hidden',
    hidden: true,
    conditions: [{ type: 'commission_streak', consecutive: 3 }],
    rewards: { coins: 350, exp: 200, rewardTickets: 2 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_hidden_full_status_task',
    name: '巅峰状态',
    description: '在小浣熊所有状态均高于80的情况下完成任务。',
    emoji: '💫',
    category: 'hidden',
    hidden: true,
    conditions: [
      { type: 'raccoon_status', statusKey: 'mood', statusValue: 80 },
      { type: 'raccoon_status', statusKey: 'energy', statusValue: 80 },
      { type: 'raccoon_status', statusKey: 'focus', statusValue: 80 },
      { type: 'raccoon_status', statusKey: 'trust', statusValue: 80 },
      { type: 'task_complete', count: 1 },
    ],
    rewards: { coins: 500, exp: 300, rewardTickets: 3 },
    claimed: false,
    progress: 0,
  },
  {
    id: 'ach_hidden_rejected_event',
    name: '硬核管理者',
    description: '在触发10次负面事件后仍然坚持完成任务。',
    emoji: '🪨',
    category: 'hidden',
    hidden: true,
    conditions: [
      { type: 'negative_events_seen', count: 10 },
      { type: 'tasks_completed', count: 1 },
    ],
    rewards: { coins: 300, exp: 180, items: ['four_leaf_clover'] },
    claimed: false,
    progress: 0,
  },
]
