import { Template } from '../types/template'

export const INITIAL_TEMPLATES: Template[] = [
  {
    id: 'market_report_gen',
    name: '市场动态报告生成器',
    description: '专为市场分析报告设计，从原始数据到正式报告一键生成，格式规范、逻辑严谨。',
    category: 'report',
    modules: ['read_text', 'extract_keyinfo', 'report_summary', 'formal'],
    level: 1,
    proficiency: 0,
    stabilityBonus: 5,
    successHistory: 0,
    failHistory: 0,
    version: 1,
    isHidden: false,
    isUserCreated: false,
    taskTags: ['research', 'analysis', 'writing'],
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'course_material_summarizer',
    name: '课程资料总结器',
    description: '将复杂的课程材料整理成清晰的学习笔记，简洁易懂，方便复习。',
    category: 'education',
    modules: ['read_text', 'summarize_content', 'concise', 'stable_optimization'],
    level: 1,
    proficiency: 0,
    stabilityBonus: 8,
    successHistory: 0,
    failHistory: 0,
    version: 1,
    isHidden: false,
    isUserCreated: false,
    taskTags: ['writing', 'research', 'communication'],
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'competitor_data_comparator',
    name: '竞品数据对比器',
    description: '系统性解析竞品数据表格，清洗整理后输出专业的对比结论报告。',
    category: 'analysis',
    modules: ['parse_table', 'clean_data', 'data_conclusion', 'professional'],
    level: 1,
    proficiency: 0,
    stabilityBonus: 6,
    successHistory: 0,
    failHistory: 0,
    version: 1,
    isHidden: false,
    isUserCreated: false,
    taskTags: ['data', 'analysis'],
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'meeting_minutes_organizer',
    name: '会议纪要整理器',
    description: '将零散的会议记录整理成标准格式的会议纪要，清晰列出决议和后续行动项。',
    category: 'planning',
    modules: ['organize_files', 'analyze_logic', 'meeting_minutes', 'formal'],
    level: 1,
    proficiency: 0,
    stabilityBonus: 7,
    successHistory: 0,
    failHistory: 0,
    version: 1,
    isHidden: false,
    isUserCreated: false,
    taskTags: ['planning', 'communication', 'writing'],
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'report_ppt_outliner',
    name: '汇报PPT大纲器',
    description: '收集汇报素材后进行推导论证，生成逻辑清晰的PPT大纲，让演示更有说服力。',
    category: 'presentation',
    modules: ['collect_info', 'deduce_reasoning', 'ppt_outline', 'formal'],
    level: 1,
    proficiency: 0,
    stabilityBonus: 5,
    successHistory: 0,
    failHistory: 0,
    version: 1,
    isHidden: false,
    isUserCreated: false,
    taskTags: ['planning', 'writing', 'communication'],
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'quick_summary_assistant',
    name: '快速摘要助手',
    description: '最轻量的摘要工具，读取文本后快速提取关键信息，以简洁风格输出核心摘要。',
    category: 'general',
    modules: ['read_text', 'extract_keyinfo', 'concise'],
    level: 1,
    proficiency: 0,
    stabilityBonus: 4,
    successHistory: 0,
    failHistory: 0,
    version: 1,
    isHidden: false,
    isUserCreated: false,
    taskTags: ['writing', 'research', 'analysis', 'communication'],
    createdAt: '2026-04-01T00:00:00Z',
  },
]
