import { Item } from '../types/inventory'

export const ITEMS: Item[] = [
  // --- Boost items ---
  {
    id: 'glow_sticker',
    name: '荧光贴纸',
    emoji: '✨',
    description: '贴在任务文件上的发光贴纸，据说能激发好运气，小幅提升任务成功率。',
    type: 'boost',
    rarity: 'common',
    price: 25,
    effects: {
      successRateBonus: 10,
    },
    usableIn: 'task',
    flavorText: '小浣熊把贴纸贴得歪歪的，但奇怪地，成功率确实提高了。',
  },
  {
    id: 'lucky_charm',
    name: '幸运符',
    emoji: '🍀',
    description: '来历不明的幸运符咒，可以显著提升执行任务时的成功率。',
    type: 'boost',
    rarity: 'uncommon',
    price: 45,
    effects: {
      successRateBonus: 15,
    },
    usableIn: 'task',
    flavorText: '字迹有些模糊，但小浣熊每次拿到它就会先闻一闻，好像能闻出幸运的味道。',
  },
  {
    id: 'four_leaf_clover',
    name: '四叶草',
    emoji: '🌿',
    description: '真正的四叶草，极为稀有，大幅提升任务成功率，是任务前的最佳护符。',
    type: 'boost',
    rarity: 'rare',
    price: 80,
    effects: {
      successRateBonus: 20,
    },
    usableIn: 'task',
    flavorText: '它是从角落里发现的，小浣熊把它压平夹在最重要的文件夹里。',
  },
  // --- Recovery items ---
  {
    id: 'energy_drink',
    name: '能量饮料',
    emoji: '🥤',
    description: '高效能量补充饮料，随时可用，快速恢复精力状态。',
    type: 'recovery',
    rarity: 'common',
    price: 20,
    effects: {
      statusRestore: { energy: 30 },
    },
    usableIn: 'anytime',
    flavorText: '拉环一开，小浣熊两耳一抖——工作魂又回来了。',
  },
  {
    id: 'mood_sticker',
    name: '心情贴纸',
    emoji: '😊',
    description: '印有可爱图案的贴纸套装，贴在桌上能改善心情，随时使用。',
    type: 'recovery',
    rarity: 'common',
    price: 18,
    effects: {
      statusRestore: { mood: 25 },
    },
    usableIn: 'anytime',
    flavorText: '贴纸上的小浣熊在微笑，看着它，自己也忍不住笑了。',
  },
  // --- Grooming ---
  {
    id: 'premium_groom_kit',
    name: '高级梳洗包',
    emoji: '🪥',
    description: '专业级毛发护理套装，一次彻底清洁，清洁度大幅恢复。',
    type: 'grooming',
    rarity: 'uncommon',
    price: 35,
    effects: {
      statusRestore: { cleanliness: 30 },
    },
    usableIn: 'care',
    flavorText: '用完之后小浣熊的毛发变得柔亮，它自己也凑到镜子前欣赏了很久。',
  },
  // --- Special items ---
  {
    id: 'repair_tape',
    name: '修复魔法带',
    emoji: '🔧',
    description: '神奇的修复胶带，可以修复受损的模板，提升模板熟练度。',
    type: 'special',
    rarity: 'rare',
    price: 90,
    effects: {
      templateProficiencyBonus: 10,
    },
    usableIn: 'task',
    flavorText: '用魔法带把破损的流程图粘好，小浣熊满意地点了点头：这下没人看出来了。',
  },
  {
    id: 'rainbow_exp_card',
    name: '彩虹经验卡',
    emoji: '🌈',
    description: '传说中的彩虹经验加速卡，下一次任务经验获得翻倍！',
    type: 'special',
    rarity: 'rare',
    price: 100,
    effects: {
      expMultiplier: 2,
    },
    usableIn: 'task',
    flavorText: '卡面在光下会变换颜色，小浣熊把它对着灯转了好几圈才舍得使用。',
  },
  {
    id: 'speed_gear',
    name: '加速齿轮',
    emoji: '⚙️',
    description: '微型机械齿轮，安装到工作流程后降低一次任务的AP消耗。',
    type: 'special',
    rarity: 'rare',
    price: 120,
    effects: {
      apCostReduction: 1,
    },
    usableIn: 'task',
    flavorText: '齿轮咬合的声音很小，但小浣熊每次听到都会露出满意的表情。',
  },
  {
    id: 'commission_voucher',
    name: '委托券',
    emoji: '📜',
    description: '神秘委托人留下的委托券，可以解锁一项特殊限时委托任务。',
    type: 'special',
    rarity: 'uncommon',
    price: 50,
    effects: {},
    usableIn: 'task',
    flavorText: '委托券上的文字用古老字体写成，小浣熊研究了很久，决定接受挑战。',
  },
  // --- Consumable ---
  {
    id: 'sleep_aroma',
    name: '助眠香薰',
    emoji: '🕯️',
    description: '天然植物香薰蜡烛，点燃后帮助小浣熊深度休息，恢复精力。',
    type: 'consumable',
    rarity: 'common',
    price: 22,
    effects: {
      statusRestore: { energy: 20 },
    },
    usableIn: 'care',
    flavorText: '香薰点燃后，小浣熊窝进软垫里，鼻子一抽一抽地睡着了。',
  },
  {
    id: 'focus_goggles',
    name: '专注护目镜',
    emoji: '🥽',
    description: '特制专注护目镜，屏蔽干扰视野，下一次任务专注力大幅提升。',
    type: 'consumable',
    rarity: 'uncommon',
    price: 40,
    effects: {
      statusRestore: { focus: 20 },
    },
    usableIn: 'task',
    flavorText: '戴上护目镜的小浣熊看起来像个小科学家，工作起来也格外认真。',
  },
  {
    id: 'trust_badge',
    name: '信任徽章',
    emoji: '🏅',
    description: '闪亮的信任徽章，佩戴它向小浣熊传达真诚，显著提升信任值。',
    type: 'consumable',
    rarity: 'uncommon',
    price: 38,
    effects: {
      statusRestore: { trust: 15 },
    },
    usableIn: 'anytime',
    flavorText: '徽章别在衣服上，小浣熊盯着它看了很久，然后走过来嗅了嗅你的手。',
  },
  {
    id: 'knowledge_crystal',
    name: '知识结晶',
    emoji: '💎',
    description: '压缩了大量知识的神秘结晶，使用后直接获得研究点数。',
    type: 'consumable',
    rarity: 'uncommon',
    price: 55,
    effects: {},
    usableIn: 'anytime',
    flavorText: '结晶在手中缓缓溶解，知识像泡泡一样升起——小浣熊感觉自己变聪明了。',
  },
  {
    id: 'magic_eraser',
    name: '魔法橡皮',
    emoji: '🧹',
    description: '能够擦除失败记录的神奇橡皮，降低指定模板的失败历史数量。',
    type: 'special',
    rarity: 'rare',
    price: 75,
    effects: {
      templateProficiencyBonus: 5,
    },
    usableIn: 'task',
    flavorText: '橡皮擦过的地方变得干净，就像那些失败从未发生一样——但教训还在心里。',
  },
]
