import { Reward } from '../types/reward'

export const REWARDS: Reward[] = [
  // ===================== IN-GAME REWARDS (FREE) =====================
  {
    id: 'reward_special_skin_raccoon',
    name: '小浣熊限定皮肤：星空版',
    description: '为小浣熊解锁星空图案的特别装扮，夜晚会发出淡淡的荧光。',
    emoji: '🌌',
    type: 'in_game',
    cost: 0,
    stock: -1,         // unlimited
    remaining: -1,
    claimCondition: 'ach_trust_100',
    needLogin: false,
    needServerValidation: false,
    deliveryType: 'in_game_grant',
    isActive: true,
  },
  {
    id: 'reward_exclusive_item_pack',
    name: '限定道具礼包',
    description: '包含彩虹经验卡×2、四叶草×1、幸运符×3的限定道具包，仅可兑换一次。',
    emoji: '🎁',
    type: 'in_game',
    cost: 5,           // rewardTickets
    stock: -1,
    remaining: -1,
    needLogin: false,
    needServerValidation: false,
    deliveryType: 'in_game_grant',
    isActive: true,
  },
  {
    id: 'reward_premium_template_shard',
    name: '高级模板碎片×10',
    description: '10枚高级模板碎片，可用于解锁或升级高级工作模板。',
    emoji: '🔮',
    type: 'in_game',
    cost: 3,
    stock: -1,
    remaining: -1,
    needLogin: false,
    needServerValidation: false,
    deliveryType: 'in_game_grant',
    isActive: true,
  },
  {
    id: 'reward_extra_ap_day',
    name: '今日AP+2',
    description: '今天的行动点数额外增加2点，让小浣熊可以完成更多任务。',
    emoji: '⚡',
    type: 'in_game',
    cost: 2,
    stock: -1,
    remaining: -1,
    needLogin: false,
    needServerValidation: false,
    deliveryType: 'in_game_grant',
    isActive: true,
  },

  // ===================== MEMBERSHIP REWARDS =====================
  {
    id: 'reward_membership_discount',
    name: '小浣熊会员优惠券',
    description: '价值50元的平台会员优惠券，可用于订阅或续费会员服务，有效期30天。',
    emoji: '🎟️',
    type: 'membership',
    cost: 10,
    stock: 100,
    remaining: 100,
    claimCondition: 'ach_login_streak_30',
    needLogin: true,
    needServerValidation: true,
    deliveryType: 'code',
    isActive: true,
    expiresAt: '2026-12-31T23:59:59Z',
  },
  {
    id: 'reward_vip_one_month',
    name: '会员月卡',
    description: '赠送一个月平台VIP会员资格，享受全功能体验。',
    emoji: '👑',
    type: 'membership',
    cost: 20,
    stock: 50,
    remaining: 50,
    claimCondition: 'ach_one_month',
    needLogin: true,
    needServerValidation: true,
    deliveryType: 'in_game_grant',
    isActive: true,
    expiresAt: '2026-12-31T23:59:59Z',
  },

  // ===================== VOUCHER REWARDS =====================
  {
    id: 'reward_coffee_voucher',
    name: '咖啡代金券',
    description: '价值30元的咖啡品牌代金券，可在指定门店使用，给自己和小浣熊各来一杯！',
    emoji: '☕',
    type: 'voucher',
    cost: 8,
    stock: 200,
    remaining: 200,
    needLogin: true,
    needServerValidation: true,
    deliveryType: 'code',
    isActive: true,
    expiresAt: '2026-06-30T23:59:59Z',
  },
  {
    id: 'reward_book_voucher',
    name: '电子书代金券',
    description: '电子书平台20元代金券，为你和小浣熊补充更多知识。',
    emoji: '📚',
    type: 'voucher',
    cost: 6,
    stock: 300,
    remaining: 300,
    needLogin: true,
    needServerValidation: true,
    deliveryType: 'code',
    isActive: true,
    expiresAt: '2026-09-30T23:59:59Z',
  },

  // ===================== PHYSICAL REWARDS =====================
  {
    id: 'reward_custom_gift_card',
    name: '定制礼物卡',
    description: '印有你和小浣熊名字的定制礼物卡，附带小浣熊形象彩绘，邮寄到家。',
    emoji: '💌',
    type: 'physical',
    cost: 15,
    stock: 50,
    remaining: 50,
    claimCondition: 'ach_trust_80',
    needLogin: true,
    needServerValidation: true,
    deliveryType: 'address',
    isActive: true,
  },
  {
    id: 'reward_activity_ticket',
    name: '线下活动门票',
    description: '参加「小浣熊养殖计划」线下体验活动的入场券，与其他训练师面对面交流！',
    emoji: '🎪',
    type: 'physical',
    cost: 30,
    stock: 30,
    remaining: 30,
    claimCondition: 'ach_login_streak_30',
    needLogin: true,
    needServerValidation: true,
    deliveryType: 'code',
    isActive: false,
    expiresAt: '2026-08-31T23:59:59Z',
  },
]
