import { Task } from '../types/task'

export const TASKS: Task[] = [
  // ===================== DAILY TASKS =====================

  // --- E Difficulty ---
  {
    id: 'daily_zoo_email_reply',
    name: '动物园合作咨询邮件回复',
    description: '某市动物园发来邮件，希望就大熊猫引进事宜展开合作咨询。请起草一封专业得体的回复邮件，说明合作流程和所需材料。',
    flavorText: '小浣熊盯着屏幕上的合作邀请，认真思考着如何在"热情"和"专业"之间找到平衡。',
    type: 'daily',
    category: 'writing',
    difficulty: 'E',
    urgency: 'low',
    baseSuccessRate: 90,
    apCost: 2,
    recommendedStats: ['expression', 'stability'],
    recommendedTemplates: ['quick_summary_assistant'],
    supportsDecompose: false,
    rewards: { coins: 30, exp: 20 },
    penalties: { mood: -5 },
    isRepeatable: true,
  },
  {
    id: 'daily_raccoon_obs_log',
    name: '浣熊活动记录整理',
    description: '将今日的浣熊行为观察数据（进食时间、活动轨迹、社交互动次数）整理成标准格式的观察日志，便于后续研究引用。',
    flavorText: '小浣熊看着关于自己同类的观察记录，觉得数据既陌生又有点面熟。',
    type: 'daily',
    category: 'data',
    difficulty: 'E',
    urgency: 'low',
    baseSuccessRate: 92,
    apCost: 2,
    recommendedStats: ['analysis', 'dexterity'],
    recommendedTemplates: ['meeting_minutes_organizer'],
    supportsDecompose: false,
    rewards: { coins: 25, exp: 15 },
    penalties: { mood: -3 },
    isRepeatable: true,
  },
  {
    id: 'daily_species_intro_draft',
    name: '物种科普简介撰写',
    description: '为研究所官网撰写一篇关于"蜜獾"的物种科普简介，要求400字以内，语言生动有趣，包含栖息地、食性和有趣行为特点。',
    flavorText: '写蜜獾要有蜜獾的气势——小浣熊捏了捏拳头，开始查资料。',
    type: 'daily',
    category: 'writing',
    difficulty: 'E',
    urgency: 'normal',
    baseSuccessRate: 88,
    apCost: 2,
    recommendedStats: ['expression', 'creativity'],
    recommendedTemplates: ['quick_summary_assistant'],
    supportsDecompose: false,
    rewards: { coins: 28, exp: 18 },
    penalties: { mood: -4 },
    isRepeatable: true,
  },

  // --- D Difficulty ---
  {
    id: 'daily_visitor_trend_analysis',
    name: '动物园客流趋势简析',
    description: '分析某市野生动物园近三个月的客流数据（工作日 vs 周末、分时段入园人数），找出规律并给出2-3条运营建议。',
    flavorText: '周末客流是工作日的3.2倍，小浣熊盯着这个数字，觉得里面藏着不止一个故事。',
    type: 'daily',
    category: 'data',
    difficulty: 'D',
    urgency: 'normal',
    baseSuccessRate: 80,
    apCost: 2,
    recommendedStats: ['analysis', 'understanding'],
    recommendedTemplates: ['competitor_data_comparator'],
    supportsDecompose: false,
    rewards: { coins: 45, exp: 35 },
    penalties: { mood: -8, trust: -2 },
    isRepeatable: true,
  },
  {
    id: 'daily_protection_weekly',
    name: '濒危物种保护周报',
    description: '汇总本周"雪豹保护项目"的工作进展：野外监测数据更新、新生幼崽记录、团队协调情况，输出一份300字的内部周报。',
    flavorText: '这周监测到两只新的雪豹幼崽——小浣熊在周报里写下这句话时，爪子微微颤抖了一下。',
    type: 'daily',
    category: 'writing',
    difficulty: 'D',
    urgency: 'normal',
    baseSuccessRate: 78,
    apCost: 2,
    recommendedStats: ['expression', 'stability'],
    recommendedTemplates: ['quick_summary_assistant'],
    supportsDecompose: false,
    rewards: { coins: 45, exp: 32 },
    penalties: { mood: -8 },
    isRepeatable: true,
  },
  {
    id: 'daily_behavior_data_clean',
    name: '动物行为数据清洗',
    description: '一份包含480条记录的灵长类动物行为数据集存在时间戳格式混乱、重复条目、异常值等问题。请制定清洗方案并输出处理后的数据质量报告。',
    flavorText: '第47行的时间戳是"2099年"，小浣熊疑惑地看了看日历——这只猴子来自未来？',
    type: 'daily',
    category: 'data',
    difficulty: 'D',
    urgency: 'normal',
    baseSuccessRate: 77,
    apCost: 2,
    recommendedStats: ['analysis', 'dexterity', 'stability'],
    recommendedTemplates: ['competitor_data_comparator'],
    supportsDecompose: false,
    rewards: { coins: 50, exp: 38, researchPoints: 5 },
    penalties: { mood: -10, trust: -3 },
    isRepeatable: true,
  },
  {
    id: 'daily_team_meeting_minutes',
    name: '野外调研团队会议纪要',
    description: '整理"东非草原野生动物迁徙观测项目"周会的讨论记录，输出标准格式的纪要，包含议题结论、待办事项及负责人。',
    flavorText: '会议上大家都在讲角马迁徙，小浣熊边记录边想：角马真的一点不嫌挤吗？',
    type: 'daily',
    category: 'planning',
    difficulty: 'D',
    urgency: 'normal',
    baseSuccessRate: 82,
    apCost: 2,
    recommendedStats: ['understanding', 'expression'],
    recommendedTemplates: ['meeting_minutes_organizer'],
    supportsDecompose: false,
    rewards: { coins: 42, exp: 32 },
    penalties: { mood: -7, trust: -2 },
    isRepeatable: true,
  },

  // --- C Difficulty ---
  {
    id: 'daily_polar_bear_research',
    name: '北极熊栖息地缩减研究综述',
    description: '梳理近五年关于北极熊栖息地面积变化的研究文献，提炼3-5个核心发现，归纳主要研究方法，并对研究空白提出建议。',
    flavorText: '小浣熊打开第十二篇文献，北极的冰越来越少，而文字越来越沉。',
    type: 'daily',
    category: 'research',
    difficulty: 'C',
    urgency: 'normal',
    baseSuccessRate: 68,
    apCost: 2,
    recommendedStats: ['understanding', 'analysis', 'expression'],
    recommendedTemplates: ['market_report_gen'],
    supportsDecompose: true,
    decomposedSteps: ['文献检索与筛选', '核心发现提炼', '研究空白分析', '综述撰写'],
    rewards: { coins: 70, exp: 55, researchPoints: 10 },
    penalties: { mood: -12, trust: -5 },
    isRepeatable: true,
  },
  {
    id: 'daily_zoo_competitor_analysis',
    name: '全国头部动物园竞品分析',
    description: '对比分析上野、长隆、济南野生动物世界三家动物园的展区设计、特色物种、门票定价和游客口碑，形成结构化竞品分析文档。',
    flavorText: '小浣熊看了三家动物园的官网，发现每家都在强调自己"最大"——这个词有点贬值了。',
    type: 'daily',
    category: 'analysis',
    difficulty: 'C',
    urgency: 'normal',
    baseSuccessRate: 65,
    apCost: 2,
    recommendedStats: ['analysis', 'understanding'],
    recommendedTemplates: ['competitor_data_comparator'],
    supportsDecompose: true,
    decomposedSteps: ['信息采集', '对比维度建立', '分析结论输出'],
    rewards: { coins: 75, exp: 58, researchPoints: 12 },
    penalties: { mood: -12, trust: -5 },
    isRepeatable: true,
  },
  {
    id: 'daily_tracking_system_req',
    name: '野生动物追踪系统需求文档',
    description: '为即将开发的"AI辅助野生动物实时追踪系统"撰写产品需求文档（PRD），包含核心功能、用户角色、技术约束和验收标准。',
    flavorText: '"要能识别出每只狮子的脸"——小浣熊听到这个需求，爪子在键盘上停了一下。',
    type: 'daily',
    category: 'planning',
    difficulty: 'C',
    urgency: 'normal',
    baseSuccessRate: 72,
    apCost: 2,
    recommendedStats: ['analysis', 'stability', 'understanding'],
    recommendedTemplates: ['meeting_minutes_organizer'],
    supportsDecompose: false,
    rewards: { coins: 65, exp: 50 },
    penalties: { mood: -10, trust: -4 },
    isRepeatable: true,
  },
  {
    id: 'daily_conservation_campaign',
    name: '世界动物日公益活动策划',
    description: '策划10月4日世界动物日的线上公益传播活动，包含主题创意、内容形式、传播渠道和预期影响力指标。',
    flavorText: '小浣熊盯着"世界动物日"，忽然想到——自己既是策划者，也是主角之一。',
    type: 'daily',
    category: 'creative',
    difficulty: 'C',
    urgency: 'normal',
    baseSuccessRate: 70,
    apCost: 2,
    recommendedStats: ['creativity', 'expression'],
    recommendedTemplates: ['quick_summary_assistant'],
    supportsDecompose: false,
    rewards: { coins: 68, exp: 52 },
    penalties: { mood: -11 },
    isRepeatable: true,
  },
  {
    id: 'daily_primate_behavior_report',
    name: '灵长类社交行为对比研究报告',
    description: '对比黑猩猩、倭黑猩猩和日本猕猴三种灵长类动物的群体合作行为、冲突解决策略，分析其社会结构异同，输出结构化研究报告。',
    flavorText: '小浣熊发现倭黑猩猩解决冲突的方式出奇平和，记下这个发现，若有所思。',
    type: 'daily',
    category: 'research',
    difficulty: 'C',
    urgency: 'normal',
    baseSuccessRate: 67,
    apCost: 2,
    recommendedStats: ['understanding', 'analysis'],
    recommendedTemplates: ['competitor_data_comparator'],
    supportsDecompose: false,
    rewards: { coins: 72, exp: 56, researchPoints: 10 },
    penalties: { mood: -12, trust: -4 },
    isRepeatable: true,
  },
  {
    id: 'daily_care_manual_chapter',
    name: '《浣熊饲养操作手册》章节撰写',
    description: '为研究所内部操作手册撰写"浣熊日常健康监测"章节，涵盖体重记录频率、异常行为识别标准及应急处置流程。',
    flavorText: '小浣熊看了一眼镜子，觉得自己特别有资格写这一章。',
    type: 'daily',
    category: 'writing',
    difficulty: 'C',
    urgency: 'low',
    baseSuccessRate: 74,
    apCost: 2,
    recommendedStats: ['expression', 'understanding', 'stability'],
    recommendedTemplates: ['quick_summary_assistant'],
    supportsDecompose: false,
    rewards: { coins: 60, exp: 48 },
    penalties: { mood: -9 },
    isRepeatable: true,
  },

  // --- B Difficulty ---
  {
    id: 'daily_urban_wildlife_viz',
    name: '城市野生动物数据可视化方案',
    description: '基于近五年城市边缘地带野生动物出没记录数据（共2.3万条），设计一套可视化方案，选择合适图表类型，说明每个图表的分析价值和实现路径。',
    flavorText: '条形图？热力图？弦图？小浣熊在草稿纸上画了又擦，数据的故事需要最合适的语言。',
    type: 'daily',
    category: 'data',
    difficulty: 'B',
    urgency: 'normal',
    baseSuccessRate: 56,
    apCost: 3,
    recommendedStats: ['analysis', 'creativity', 'dexterity'],
    recommendedTemplates: ['competitor_data_comparator'],
    supportsDecompose: false,
    rewards: { coins: 120, exp: 95, researchPoints: 18 },
    penalties: { mood: -18, trust: -8 },
    isRepeatable: false,
  },
  {
    id: 'daily_zoo_interview_analysis',
    name: '动物园数字化改造用户访谈分析',
    description: '分析对15位动物园运营管理人员的深度访谈记录，提炼用户在"数字化管理工具"方面的核心需求、主要痛点和未被满足的期望。',
    flavorText: '小浣熊把所有访谈便利贴贴满了一整面墙，退后三步——规律开始浮现了。',
    type: 'daily',
    category: 'research',
    difficulty: 'B',
    urgency: 'normal',
    baseSuccessRate: 58,
    apCost: 3,
    recommendedStats: ['understanding', 'analysis', 'expression'],
    recommendedTemplates: ['market_report_gen'],
    supportsDecompose: true,
    decomposedSteps: ['访谈记录梳理', '主题归纳聚类', '洞察提炼排序', '报告撰写'],
    rewards: { coins: 125, exp: 98, researchPoints: 20 },
    penalties: { mood: -18, trust: -8 },
    isRepeatable: false,
  },
  {
    id: 'daily_conservation_kpi_dashboard',
    name: '物种保育季度KPI看板设计',
    description: '为"华南虎人工繁育项目"设计季度KPI监控看板，包含种群数量、健康指数、繁育成功率等核心指标，说明数据来源、更新频率及预警阈值。',
    flavorText: '小浣熊把"种群基因多样性指数"这个指标写进KPI，觉得它应该早就在里面了。',
    type: 'daily',
    category: 'data',
    difficulty: 'B',
    urgency: 'normal',
    baseSuccessRate: 55,
    apCost: 3,
    recommendedStats: ['analysis', 'understanding', 'dexterity'],
    recommendedTemplates: ['competitor_data_comparator'],
    supportsDecompose: false,
    rewards: { coins: 118, exp: 92, researchPoints: 16 },
    penalties: { mood: -16, trust: -7 },
    isRepeatable: false,
  },

  // --- A Difficulty ---
  {
    id: 'daily_annual_ppt',
    name: '动物研究所年度工作汇报PPT',
    description: '制作完整的年度汇报演示文稿：涵盖全年科研产出（发表论文8篇）、重点保护项目进展（7个项目）、经费使用与来年预算申请，共需约30页。',
    flavorText: '三十页PPT，小浣熊先列出目录，深吸一口气，从"2024年度亮点"开始。',
    type: 'daily',
    category: 'planning',
    difficulty: 'A',
    urgency: 'urgent',
    baseSuccessRate: 42,
    apCost: 3,
    recommendedStats: ['analysis', 'expression', 'understanding', 'stability'],
    recommendedTemplates: ['report_ppt_outliner', 'market_report_gen'],
    supportsDecompose: true,
    decomposedSteps: ['数据与成果汇总', '亮点案例提炼', '问题与展望', 'PPT结构与内容设计'],
    rewards: { coins: 220, exp: 175, researchPoints: 35, rewardTickets: 1 },
    penalties: { mood: -28, trust: -14, coins: -60 },
    isRepeatable: false,
  },
  {
    id: 'daily_strategy_analysis',
    name: '中国野生动物保护行业战略分析',
    description: '运用SWOT+PESTLE双框架，对中国野生动物保护行业进行深度战略分析，梳理政策机遇、技术趋势、资金挑战及竞争格局，输出战略建议报告。',
    flavorText: '小浣熊在白板上密密麻麻画满了框和箭头——战略分析就是把复杂世界变成可以行动的地图。',
    type: 'daily',
    category: 'analysis',
    difficulty: 'A',
    urgency: 'normal',
    baseSuccessRate: 40,
    apCost: 3,
    recommendedStats: ['analysis', 'understanding', 'stability'],
    recommendedTemplates: ['market_report_gen', 'competitor_data_comparator'],
    supportsDecompose: true,
    decomposedSteps: ['外部环境分析(PESTLE)', '内部能力评估(SWOT)', '战略选项推导', '报告撰写'],
    rewards: { coins: 240, exp: 190, researchPoints: 38, rewardTickets: 1 },
    penalties: { mood: -30, trust: -15, coins: -70 },
    isRepeatable: false,
  },
  {
    id: 'daily_habitat_feasibility',
    name: '云南红河谷栖息地恢复可行性研究',
    description: '针对云南红河谷地区开展野生动物栖息地恢复可行性研究：评估植被状况、水源分布、人为干扰程度，论证恢复方案的技术可行性和预期效益。',
    flavorText: '小浣熊翻出卫星地图，开始测量可利用的植被覆盖面积——这片土地值得被认真对待。',
    type: 'daily',
    category: 'research',
    difficulty: 'A',
    urgency: 'normal',
    baseSuccessRate: 44,
    apCost: 3,
    recommendedStats: ['understanding', 'analysis', 'expression'],
    recommendedTemplates: ['market_report_gen'],
    supportsDecompose: true,
    decomposedSteps: ['现状调研与数据采集', '多方案对比评估', '风险与效益分析', '可研报告撰写'],
    rewards: { coins: 210, exp: 168, researchPoints: 32 },
    penalties: { mood: -25, trust: -12, coins: -50 },
    isRepeatable: false,
  },
  {
    id: 'daily_research_proposal',
    name: '跨机构合作研究课题申报书',
    description: '联合三家高校动物学系，撰写"气候变化对中国鸟类迁徙路线影响"国家自然科学基金重点项目申报书，包含研究背景、科学问题、技术方案及预期成果。',
    flavorText: '从一个模糊的观察——"鸟来得越来越晚了"——到一份严格的科研申报，这是小浣熊最喜欢的蜕变。',
    type: 'daily',
    category: 'research',
    difficulty: 'A',
    urgency: 'low',
    baseSuccessRate: 45,
    apCost: 3,
    recommendedStats: ['understanding', 'analysis', 'creativity'],
    recommendedTemplates: ['market_report_gen'],
    supportsDecompose: true,
    decomposedSteps: ['科学问题凝练', '文献综述撰写', '技术路线设计', '申报书整合'],
    rewards: { coins: 205, exp: 164, researchPoints: 42 },
    penalties: { mood: -22, trust: -11 },
    isRepeatable: false,
  },

  // ===================== COMMISSION TASKS (8) =====================

  {
    id: 'comm_epidemic_summary',
    name: '【紧急】禽流感疫情快报摘要',
    description: '【紧急委托】东南亚多地爆发新型禽流感疫情，需在2小时内提供面向管理层的疫情快报摘要：波及地区、受影响物种、防控建议、对研究所工作的潜在影响。',
    flavorText: '委托电话只有一句话："所长需要在下午3点之前看到这份东西。"小浣熊已经开始打字了。',
    type: 'commission',
    category: 'writing',
    difficulty: 'C',
    urgency: 'immediate',
    baseSuccessRate: 62,
    apCost: 3,
    recommendedStats: ['expression', 'understanding', 'stability'],
    recommendedTemplates: ['meeting_minutes_organizer'],
    supportsDecompose: false,
    rewards: { coins: 160, exp: 90, rewardTickets: 1 },
    penalties: { mood: -22, trust: -12, coins: -35 },
    isRepeatable: false,
  },
  {
    id: 'comm_esg_animal_index',
    name: '企业动物福利ESG指数调研报告',
    description: '【重要委托】某头部投资机构委托调研：评估国内前20家上市动物相关企业的动物福利实践，建立评分维度体系，输出完整调研报告及企业排名。',
    flavorText: '委托人说："我们需要一套可以被信任的标准。"小浣熊深以为然，认真开始搭建框架。',
    type: 'commission',
    category: 'research',
    difficulty: 'B',
    urgency: 'urgent',
    baseSuccessRate: 52,
    apCost: 3,
    recommendedStats: ['analysis', 'understanding', 'expression'],
    recommendedTemplates: ['market_report_gen', 'competitor_data_comparator'],
    supportsDecompose: true,
    decomposedSteps: ['评估维度设计', '企业数据采集', '评分模型搭建', '报告撰写与排名'],
    rewards: { coins: 260, exp: 190, researchPoints: 28, rewardTickets: 2 },
    penalties: { mood: -32, trust: -16, coins: -90 },
    isRepeatable: false,
  },
  {
    id: 'comm_ai_behavior_proposal',
    name: 'AI辅助动物行为识别系统方案书',
    description: '【技术委托】为某动物园起草"基于计算机视觉的动物异常行为智能识别系统"建设方案，包含系统架构设计、AI模型选型、数据标注需求、实施路径和预算估算。',
    flavorText: '"让AI认出每只动物是否开心"——这个需求让小浣熊觉得科技和善意终于走在一起了。',
    type: 'commission',
    category: 'planning',
    difficulty: 'B',
    urgency: 'urgent',
    baseSuccessRate: 50,
    apCost: 3,
    recommendedStats: ['analysis', 'stability', 'understanding'],
    recommendedTemplates: ['report_ppt_outliner', 'meeting_minutes_organizer'],
    supportsDecompose: true,
    decomposedSteps: ['需求分析与系统设计', 'AI技术方案选型', '数据与实施路径规划', '方案书整合'],
    rewards: { coins: 245, exp: 180, researchPoints: 22, rewardTickets: 1 },
    penalties: { mood: -27, trust: -13, coins: -70 },
    isRepeatable: false,
  },
  {
    id: 'comm_fundraising_pitch',
    name: '野生动物保护基金融资路演PPT',
    description: '【创意委托】为"亚洲野生动物紧急保护基金"制作融资路演演示文稿（15页），面向国际环保基金会，需涵盖使命愿景、项目亮点、资金用途、影响力数据和合作邀约。',
    flavorText: '"帮我们把这份善意变成可以被资助的事业"——小浣熊认为这是最值得做好的PPT。',
    type: 'commission',
    category: 'creative',
    difficulty: 'B',
    urgency: 'normal',
    baseSuccessRate: 54,
    apCost: 3,
    recommendedStats: ['creativity', 'expression', 'understanding'],
    recommendedTemplates: ['report_ppt_outliner'],
    supportsDecompose: false,
    rewards: { coins: 235, exp: 172, rewardTickets: 1 },
    penalties: { mood: -24, trust: -11, coins: -60 },
    isRepeatable: false,
  },
  {
    id: 'comm_social_education_matrix',
    name: '动物科普社媒内容矩阵方案',
    description: '【社交委托】策划面向Z世代的野生动物科普短视频内容矩阵：确定6个系列主题（如"动物职场人"、"野外生存大赛"），设计各平台差异化运营策略和内容日历。',
    flavorText: '小浣熊看着"动物职场人"这个选题，觉得这个系列第一集应该拍自己。',
    type: 'commission',
    category: 'social',
    difficulty: 'C',
    urgency: 'normal',
    baseSuccessRate: 65,
    apCost: 2,
    recommendedStats: ['creativity', 'expression', 'analysis'],
    recommendedTemplates: ['report_ppt_outliner'],
    supportsDecompose: false,
    rewards: { coins: 168, exp: 105 },
    penalties: { mood: -18, trust: -8 },
    isRepeatable: false,
  },
  {
    id: 'comm_ethics_review',
    name: '动物行为实验伦理审查报告',
    description: '【审查委托】对"捕食者气味对小型哺乳动物应激反应"实验方案进行伦理审查，依据3R原则（替代、减少、优化）评估实验设计的合规性，提出修改建议。',
    flavorText: '小浣熊阅读实验方案时，注意到受试动物的物种名单里有自己的近亲——审查更加认真了。',
    type: 'commission',
    category: 'analysis',
    difficulty: 'B',
    urgency: 'normal',
    baseSuccessRate: 48,
    apCost: 3,
    recommendedStats: ['analysis', 'understanding', 'stability'],
    recommendedTemplates: ['market_report_gen'],
    supportsDecompose: false,
    rewards: { coins: 270, exp: 195, researchPoints: 30, rewardTickets: 2 },
    penalties: { mood: -28, trust: -14, coins: -85 },
    isRepeatable: false,
  },
  {
    id: 'comm_rescue_site_analysis',
    name: '野生动物救助中心选址分析报告',
    description: '【数据委托】综合分析四川盆地周边候选地块（面积、交通、水源、周边人口密度、历史动物出没记录），用多因子加权评分模型推荐最优选址，并说明决策依据。',
    flavorText: '十二个候选地块铺在地图上，小浣熊开始计算——救助中心的位置关乎太多生命。',
    type: 'commission',
    category: 'data',
    difficulty: 'C',
    urgency: 'urgent',
    baseSuccessRate: 60,
    apCost: 3,
    recommendedStats: ['analysis', 'understanding', 'dexterity'],
    recommendedTemplates: ['competitor_data_comparator'],
    supportsDecompose: true,
    decomposedSteps: ['选址因子权重设计', '候选地块数据采集', '评分模型计算', '分析报告撰写'],
    rewards: { coins: 188, exp: 138, researchPoints: 22 },
    penalties: { mood: -23, trust: -11, coins: -55 },
    isRepeatable: false,
  },
  {
    id: 'comm_conference_speech',
    name: '世界动物园协会年会主旨发言稿',
    description: '【高级委托】为研究所所长起草在世界动物园和水族馆协会（WAZA）年会上的主旨发言（15分钟，约2000字），主题：AI技术赋能野生动物保护的中国实践。',
    flavorText: '"CEO只有两分钟阅读时间，所长有十五分钟——但听众来自全球，每个字都要值得被翻译。"',
    type: 'commission',
    category: 'communication',
    difficulty: 'A',
    urgency: 'urgent',
    baseSuccessRate: 38,
    apCost: 3,
    recommendedStats: ['expression', 'understanding', 'analysis', 'stability'],
    recommendedTemplates: ['market_report_gen', 'quick_summary_assistant'],
    supportsDecompose: false,
    rewards: { coins: 380, exp: 270, researchPoints: 45, rewardTickets: 3 },
    penalties: { mood: -42, trust: -22, coins: -130 },
    isRepeatable: false,
  },
]

// ===================== PERMANENT TASKS (always available) =====================

export const PERMANENT_TASKS: Task[] = [
  {
    id: 'perm_obs_log',
    name: '今日动物观察日志',
    description: '记录今天观察到的一个有趣动物行为，用结构化格式（时间、地点、行为描述、初步分析）整理成观察日志条目。',
    flavorText: '小浣熊拿出记录本——每一条观察都可能是未来研究的起点。',
    type: 'permanent',
    category: 'writing',
    difficulty: 'E',
    urgency: 'low',
    baseSuccessRate: 90,
    apCost: 1,
    recommendedStats: ['expression', 'stability'],
    recommendedTemplates: [],
    supportsDecompose: false,
    rewards: { coins: 15, exp: 10 },
    penalties: { mood: -2 },
    isRepeatable: true,
  },
  {
    id: 'perm_data_verify',
    name: '数据快速核验',
    description: '抽查一份研究数据表的10%样本，核验数值合理性、单位一致性和格式规范，输出核验摘要。',
    flavorText: '小浣熊的眼睛快速扫过数字，异常值就像草丛里的蟋蟀——躲不过的。',
    type: 'permanent',
    category: 'data',
    difficulty: 'E',
    urgency: 'low',
    baseSuccessRate: 92,
    apCost: 1,
    recommendedStats: ['analysis', 'dexterity'],
    recommendedTemplates: [],
    supportsDecompose: false,
    rewards: { coins: 12, exp: 12 },
    penalties: {},
    isRepeatable: true,
  },
  {
    id: 'perm_logic_puzzle',
    name: '逻辑推理训练',
    description: '完成一道关于动物学研究中的逻辑推理题（如：根据已知条件推断最优采样方案），锻炼分析思维。',
    flavorText: '小浣熊拿起铅笔，格子里的数字开始浮现出隐藏的规律。',
    type: 'permanent',
    category: 'analysis',
    difficulty: 'D',
    urgency: 'low',
    baseSuccessRate: 80,
    apCost: 1,
    recommendedStats: ['analysis', 'stability'],
    recommendedTemplates: [],
    supportsDecompose: false,
    rewards: { coins: 20, exp: 15 },
    penalties: { mood: -3 },
    isRepeatable: true,
  },
  {
    id: 'perm_species_lookup',
    name: '物种信息速查整理',
    description: '查询并整理一种小众动物（本次：马达加斯加指猴）的基本信息：分类地位、分布范围、保护级别、主要威胁，形成标准化物种卡片。',
    flavorText: '指猴的手指细长奇特，小浣熊觉得它比自己的爪子还能抠缝隙。',
    type: 'permanent',
    category: 'research',
    difficulty: 'E',
    urgency: 'low',
    baseSuccessRate: 91,
    apCost: 1,
    recommendedStats: ['understanding', 'dexterity'],
    recommendedTemplates: [],
    supportsDecompose: false,
    rewards: { coins: 14, exp: 11 },
    penalties: {},
    isRepeatable: true,
  },
  {
    id: 'perm_read_summarize',
    name: '文献速读摘要',
    description: '阅读一篇动物行为学或保护生物学相关论文的摘要与结论，用100字以内提炼核心发现，标注研究方法和局限性。',
    flavorText: '小浣熊合上文章，闭眼默想——能用一句话说清楚，才是真的读懂了。',
    type: 'permanent',
    category: 'analysis',
    difficulty: 'D',
    urgency: 'low',
    baseSuccessRate: 78,
    apCost: 2,
    recommendedStats: ['understanding', 'expression'],
    recommendedTemplates: ['quick_summary_assistant'],
    supportsDecompose: false,
    rewards: { coins: 25, exp: 20 },
    penalties: { mood: -4 },
    isRepeatable: true,
  },
  {
    id: 'perm_daily_standup',
    name: '研究团队晨会汇报',
    description: '用"三句话格式"汇报：①昨日进展（具体到数据点）②今日计划（具体到任务）③风险与阻碍，要求简洁有力，不超过90秒。',
    flavorText: '"昨天、今天、阻碍"——小浣熊觉得这三个问题问清楚了，团队就不会迷路。',
    type: 'permanent',
    category: 'communication',
    difficulty: 'E',
    urgency: 'normal',
    baseSuccessRate: 90,
    apCost: 1,
    recommendedStats: ['expression', 'stability'],
    recommendedTemplates: [],
    supportsDecompose: false,
    rewards: { coins: 16, exp: 12 },
    penalties: {},
    isRepeatable: true,
  },
]
