import { TemplateModule } from '../types/template'

export const TEMPLATE_MODULES: TemplateModule[] = [
  // ========= INPUT (5) =========
  {
    id: 'read_text',
    name: '文本阅读',
    category: 'input',
    description: '读取并解析文本内容，提取基本信息结构。',
    successBonus: 5,
    tags: ['writing', 'research', 'planning', 'communication'],
  },
  {
    id: 'parse_table',
    name: '表格解析',
    category: 'input',
    description: '识别并解析结构化表格数据，提取行列信息。',
    successBonus: 6,
    tags: ['data', 'analysis', 'research'],
  },
  {
    id: 'recognize_image',
    name: '图像识别',
    category: 'input',
    description: '识别图片中的文字、图表和视觉信息。',
    successBonus: 4,
    tags: ['creative', 'research', 'data'],
  },
  {
    id: 'organize_files',
    name: '文件整理',
    category: 'input',
    description: '系统性整理多个文件，建立清晰的信息层级。',
    successBonus: 5,
    tags: ['planning', 'data', 'analysis'],
  },
  {
    id: 'collect_info',
    name: '信息采集',
    category: 'input',
    description: '从多个来源收集相关信息，建立信息库。',
    successBonus: 5,
    tags: ['research', 'analysis', 'planning'],
  },

  // ========= PROCESS (5) =========
  {
    id: 'extract_keyinfo',
    name: '关键信息提取',
    category: 'process',
    description: '从大量信息中精准提取关键数据和要点。',
    successBonus: 7,
    tags: ['analysis', 'research', 'writing', 'planning'],
  },
  {
    id: 'clean_data',
    name: '数据清洗',
    category: 'process',
    description: '去除冗余和错误数据，标准化数据格式。',
    successBonus: 6,
    tags: ['data', 'analysis'],
  },
  {
    id: 'analyze_logic',
    name: '逻辑分析',
    category: 'process',
    description: '对信息进行逻辑推断，建立因果关系链条。',
    successBonus: 8,
    tags: ['analysis', 'research', 'planning'],
  },
  {
    id: 'deduce_reasoning',
    name: '推导论证',
    category: 'process',
    description: '通过演绎推理得出结论，构建论证框架。',
    successBonus: 7,
    tags: ['analysis', 'research', 'writing'],
  },
  {
    id: 'summarize_content',
    name: '内容总结',
    category: 'process',
    description: '将复杂内容压缩为精炼的摘要，保留核心信息。',
    successBonus: 6,
    tags: ['writing', 'communication', 'research'],
  },

  // ========= OUTPUT (5) =========
  {
    id: 'meeting_minutes',
    name: '会议纪要',
    category: 'output',
    description: '生成标准格式的会议纪要，包含决议和行动项。',
    successBonus: 6,
    tags: ['planning', 'communication', 'writing'],
  },
  {
    id: 'report_summary',
    name: '报告汇总',
    category: 'output',
    description: '生成完整的报告文档，结构清晰，逻辑严谨。',
    successBonus: 8,
    tags: ['analysis', 'research', 'writing'],
  },
  {
    id: 'data_conclusion',
    name: '数据结论',
    category: 'output',
    description: '将数据分析结果转化为可执行的结论和建议。',
    successBonus: 7,
    tags: ['data', 'analysis'],
  },
  {
    id: 'ppt_outline',
    name: 'PPT大纲',
    category: 'output',
    description: '生成清晰的演示文稿大纲，每页有明确的核心信息。',
    successBonus: 6,
    tags: ['planning', 'communication', 'writing'],
  },
  {
    id: 'action_list',
    name: '行动清单',
    category: 'output',
    description: '输出结构化的行动项清单，包含责任人和截止时间。',
    successBonus: 5,
    tags: ['planning', 'communication'],
  },

  // ========= STYLE (5) =========
  {
    id: 'formal',
    name: '正式风格',
    category: 'style',
    description: '采用严谨、规范的正式语言风格，适合商务场合。',
    successBonus: 5,
    tags: ['writing', 'analysis', 'planning', 'communication'],
  },
  {
    id: 'concise',
    name: '简洁风格',
    category: 'style',
    description: '精炼表达，去除冗余，每句话都直达要点。',
    successBonus: 6,
    tags: ['writing', 'communication', 'planning'],
  },
  {
    id: 'vivid',
    name: '生动风格',
    category: 'style',
    description: '使用丰富的修辞和生动的描述，增强文字感染力。',
    successBonus: 5,
    tags: ['creative', 'writing', 'communication'],
  },
  {
    id: 'professional',
    name: '专业风格',
    category: 'style',
    description: '运用行业术语和专业表达，彰显专业度和权威性。',
    successBonus: 6,
    tags: ['analysis', 'research', 'data'],
  },
  {
    id: 'casual',
    name: '轻松风格',
    category: 'style',
    description: '亲切自然的表达风格，适合内部沟通和轻松场合。',
    successBonus: 4,
    tags: ['social', 'communication', 'creative'],
  },

  // ========= OPTIMIZE (5) =========
  {
    id: 'stable_optimization',
    name: '稳定优化',
    category: 'optimize',
    description: '优先保证输出稳定性，减少随机波动，确保一致质量。',
    successBonus: 8,
    tags: ['writing', 'data', 'planning', 'analysis'],
  },
  {
    id: 'speed_optimization',
    name: '速度优化',
    category: 'optimize',
    description: '大幅降低AP消耗，以速度换效率，适合紧急任务。',
    successBonus: 3,
    tags: ['planning', 'communication', 'writing'],
  },
  {
    id: 'quality_optimization',
    name: '质量优化',
    category: 'optimize',
    description: '提升输出精细度，增加获得优秀和完美评级的概率。',
    successBonus: 10,
    tags: ['analysis', 'research', 'writing'],
  },
  {
    id: 'cost_reduction',
    name: '成本削减',
    category: 'optimize',
    description: '减少资源消耗，让同等输出所需AP降低。',
    successBonus: 4,
    tags: ['data', 'planning'],
  },
  {
    id: 'enhance_expression',
    name: '表达增强',
    category: 'optimize',
    description: '强化语言表达，提升文字的说服力和可读性。',
    successBonus: 7,
    tags: ['writing', 'creative', 'communication', 'social'],
  },
]
